CREATE TABLE IF NOT EXISTS ELEVE (
    ID_ELEVE INTEGER PRIMARY KEY NOT NULL,
    NOM_ELEVE CHAR(20),
    PRENOM_ELEVE CHAR(20),
    ID_GROUPE INTEGER
);

CREATE TABLE IF NOT EXISTS ENSEIGNANT (
    NOM_ENSEIGNANT CHAR(20) NOT NULL,
    PRENOM_ENSEIGNANT CHAR(20),
    PRIMARY KEY (NOM_ENSEIGNANT)
);

CREATE TABLE IF NOT EXISTS ENSEIGNER (
    NOM_MATIERE CHAR(20) NOT NULL,
    NOM_ENSEIGNANT CHAR(20) NOT NULL,
    PRIMARY KEY (NOM_MATIERE,  NOM_ENSEIGNANT),
    FOREIGN KEY (NOM_MATIERE) REFERENCES MATIERE (NOM_MATIERE),
    FOREIGN KEY (NOM_ENSEIGNANT) REFERENCES ENSEIGNANT (NOM_ENSEIGNANT)
);

CREATE TABLE IF NOT EXISTS GROUPE (
    ID_GROUPE INTEGER NOT NULL,
    NUMERO_GROUPE INTEGER,
    NOM_NIVEAU CHAR(20),
    PRIMARY KEY (ID_GROUPE),
    FOREIGN KEY (NOM_NIVEAU) REFERENCES NIVEAU (NOM_NIVEAU)
);

CREATE TABLE IF NOT EXISTS JOUR (
    NOM_JOUR CHAR(8) NOT NULL,
    PRIMARY KEY (NOM_JOUR)
);

CREATE TABLE IF NOT EXISTS MATIERE (
    NOM_MATIERE CHAR(20) NOT NULL,
    PRIMARY KEY (NOM_MATIERE)
);

CREATE TABLE IF NOT EXISTS NIVEAU (
    NOM_NIVEAU CHAR(20) NOT NULL,
    PRIMARY KEY (NOM_NIVEAU)
);

CREATE TABLE IF NOT EXISTS SALLE (
    NOM_SALLE CHAR(20) NOT NULL,
    LOGO_SALLE CHAR(40),
    PRIMARY KEY (NOM_SALLE)
);


CREATE TABLE IF NOT EXISTS TRANCHE_HORAIRE (
    ID_TRANCHE_HORAIRE INTEGER NOT NULL,
    HD_TRANCHE_HORAIRE INTEGER,
    HF_TRANCHE_HORAIRE INTEGER,
    PRIMARY KEY (ID_TRANCHE_HORAIRE)
);

CREATE TABLE IF NOT EXISTS TYPE_MATIERE (
    TYPE CHAR(2) NOT NULL,
    PRIMARY KEY (TYPE)
);

CREATE TABLE IF NOT EXISTS COURS (
    ID_TRANCHE_HORAIRE INTEGER NOT NULL ,
    ID_GROUPE INTEGER NOT NULL,
    NOM_JOUR CHAR(10) NOT NULL ,
    NOM_MATIERE CHAR(20) NOT NULL ,
    NOM_SALLE CHAR(20) NOT NULL ,
    TYPE CHAR(2) NOT NULL
    FOREIGN KEY (ID_TRANCHE_HORAIRE) REFERENCES TRANCHE_HORAIRE,
    FOREIGN KEY (ID_GROUPE) REFERENCES GROUPE,
    FOREIGN KEY (NOM_JOUR) REFERENCES JOUR,
    FOREIGN KEY (NOM_MATIERE) REFERENCES MATIERE,
    FOREIGN KEY (NOM_SALLE) REFERENCES SALLE,
    FOREIGN KEY (TYPE) REFERENCES TYPE_MATIERE,
);
